### PR TITLE
Use spaces instead of tabs for indenting XML files

### PR DESCRIPTION
**Pull request by johschmitz**
Since most of the code base uses spaces and most projects use spaces nowadays I
believe this is a reasonable change.e.

### CODE REVIEW

**Comment by johschmitz** [comment]
@maintainer: Feel free to edit the pull request and make it 4 instead of 2 spaces if you believe that is better.

**Comment by johschmitz** [comment]
I have put it to two spaces according to this answer:
https://stackoverflow.com/questions/2678817/2-spaces-or-1-tab-whats-the-standard-for-indentation-in-the-rails-community

**Comment by johschmitz** [comment]
@maintainer: Make it 4 spaces if you feel that that is better.

**Comment by mander76** [comment]
You know this is only for displaying? not for actual generation of the .xmls

**Comment by johschmitz** [comment]
I see it in my XMLs so I changed it and created the pull request. Can show
you an example if needed.

mander76 ***@***.***> schrieb am Mo., 22. März 2021, 10:47:

**Comment by johschmitz** [comment]
@mander76: I updated the pull request. Does it work now for you?

**Pull request merged**
