### PR TITLE
Add github actions for formatting and test

### PR DESCRIPTION
**Pull request by hoxovic**
I'd like to suggest using github actions to run the tests and formatting checks on PRs and pushes to automate the testing and enforce formatting.

I have no desire to propose exactly which format to use, but due to its simplicity and popularity, I went with `black` and its default configuration as an example.

What are your opinions?

(The current format is not black compliant, so if you agree with this proposal, I'll add another commit that fixes the formatting before this PR is merged.)

### CODE REVIEW

**Comment by MandolinMicke** [comment]
This is super nice. I'm still a github noob when it comes to these things. Will try to get some time to looks at these things

**Comment by hoxovic** [comment]
Feel free to try it out :) You can set it up for another branch than main to try it out first (although the badge in the readme won't work with the current url/parameter in that case)

**Comment by mander76** [comment]
I have no real opinion when it comes to the format to choose, but I have colleagues using black, and as you mentioned it's the most used one (even though I personally prefer ' instead of ")

**Comment by hoxovic** [comment]
I've applied the default black formatting and fixed a minor mistake on my part that caused the installation of the package to fail in the CI due to permission errors. The jobs are all green in my fork, so now it's only a matter of whether you think the proposed setup is a good change or not :)

**Comment by mander76** [comment]
This is great! Thanks a lot for this! :)

**Comment by hoxovic** [comment]
Happy to help. Thanks for a great tool :)

**Pull request merged**
