### PR TITLE
Write OpenDRIVE xmls utf-8 encoded

### PR DESCRIPTION
**Pull request by jakobkaths**
We want to write Chinese characters into OpenDRIVE files to display Chinese traffic signs with types according to the Chinese standards. This is currently not possible with the write function. There is some handling of the encoding, but upon actual creation of the file, the UTF-8 encoding is not passed, hence special characters are broken or files are not generated. Not sure if 
a) it is generally acceptable to use UTF-8 encoding for the output files. For our implementation it's ok, but alternatively it would of course be possible to add the encoding as another named argument to avoid changing the current output.
b) if it makes sense to add/change this in other places (like the general pretty print helper function, the xosc generation... ?)

### CODE REVIEW

**Comment by mander76** [comment]
Hmm interesting problem.
Encodings are sadly enough not my main strengths. But in general, it might be good to have it as an optional input, with utf-8 as default maybe? (or is the standard different between linux/windows/mac?)

I have to look into the code a little to see if there are more places where this might be applicable. as you mentioned, the xosc module is one, but maybe in the scenariogenerator class aswell..

**Comment by jakobkaths** [comment]
Not my strength either, but this article gave me a much better understanding and actually also helped for this small fix: https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/
Let me know if I can provide further help with the implementation. Other OS I can't really judge, but I think that should be fine, all plain Python that I used there. But I'm happy if someone can test it (I only tried windows).

**Comment by mander76** [comment]
That was a good read for a noob like me :) 

Will check if there are other places to add it to

**Comment by mander76** [comment]
Tried it on ubuntu and looks like it should. 
Can I ask you to add it to the xosc module aswell as the prettyprint functions?

**Comment by jakobkaths** [comment]
Thanks for testing, @mander76 . I hope it didn't get out of hand now, but I wanted to:

- make the encoding configurable
- add it to the functions you mentioned
- avoid code duplication

The last point led me to remove the dedicated helpers modules and integrate it all in the main one and refactor the functions a bit. My intention was to not break any interfaces, so users shouldn't actually notice anything. But please test again, I only ran some of the examples now and for me it worked.

**Comment by mander76** [comment]
Looks good, will test it a little before merge.

**Comment by jakobkaths** [comment]
Great, thanks for testing and merging. Is there any plan for a release of a new version on PyPI soon?

**Comment by mander76** [comment]
We are working on the parsing of xosc files to return the python objects, we are like 60 % done now. 
So when that is done with that I'll create a new PyPI version. (maybe a week or two hopefully)

**Comment by jakobkaths** [comment]
Ok, thanks for the info!

**Pull request merged**
