### PR TITLE
added FinalSpeed, AbsoluteSpeed, RelativeSpeedToMaster and SteadyState

### PR DESCRIPTION
**Pull request by johannesWen**

### CODE REVIEW

**Comment by mander76** [comment]
I like the idea. Some comments though.

I guess this is your idea of having one class for the SynchronizeAction? Is the Idea then to replace both RelativeSyncronizeAction and AbsoluteSyncronizeAction with this (lets call it just SyncronizeAction in that case). It was divided in the beginning not to have  to have super complex inputs. Hence most Absolute and Relative actions are separated (similar to SpeedActions and LaneOffsetActions).
Another thing with this is to reduce the amount of unneccesary layers. Eg. FinalSpeed is not needed as a class, it can be created in the SyncronizeAction itself, and just append the AbsoluteSpeed or RelativeSpeedToMaster in that case. 

In this case aswell, the action is avaiable in V1.0, in your implementation now, if you ask for a 1.0 version it will fail.

**Comment by johannesWen** [comment]
Yes, I see. You are right. I will change it that way 👍

**Comment by mander76** [comment]
Looks better. 
One thing I'm not sure about though is the version check in the __init__, I think this might cause a problem. Since the version is set when the Scenario object is created (otherwise just default the latest version), my guess is that it won't actually ever catch that the version is wrong. (unless you create the Scenario in the beginning of your script)

**Comment by mander76** [comment]
Sorry, have been really busy the past week to look into this. But now I had some spare time :) 

Only one thing is now missing ;) the tests, A simple tests is there for all classes, construction, that it can create an element, and the eq, neq .

**Pull request merged**
