### PR TITLE
Avoid width and link record within centerlanes

### PR DESCRIPTION
**Pull request by jakobkaths**
- according to standard width shall not be provided as a record for centerlanes
- also link record can be dropped as they are not linked

### CODE REVIEW

**Comment by mander76** [comment]
You are correct!
I wonder if we can include the laneoffset using a similar implementat (that can be used for the centerlane), could this be combined somehow (two birds with one stone)? So that if a lane is created for the centerlane it is set as lane-offset instead of width? The input is the same, but some different naming ( soffset vs. s)?

**Comment by jakobkaths** [comment]
Seems like a good idea. I didn't have time for extensive testing and I'm not sure if this is "clean" enough. But it would work I think. I also added a little mini feature on this PR (naming of junction) and a hard switch to type 'none' for centerlanes. If you disagree with that, you may drop that commit. It's not defined hard in the standard, but it seems to be good practice to define centerlanes as 'none'.

**Comment by mander76** [comment]
This looks good, and it seams to work with our things aswell.
Just a question, is the junction name used anywhere? or is this related to different versions as the other issue? Since I usually add these things when creating the classes.

**Comment by jakobkaths** [comment]
I'm not sure I got your question. Before the 'my junction' was hardcoded (to avoid changes I left it like that) and would always lead to having this name for all junctions in the OpenDRIVE when you use the convenience function 'create_junction()' to create the junction automatically. Now you could optionally hand over a different name. But maybe there was another way to do that and I missed this?

**Comment by jakobkaths** [comment]
Ah, maybe I got it now, do you overwrite this dummy name after creating the junction?

**Comment by mander76** [comment]
Ah, sorry my bad. I didn't read the change correctly. 
Will merge

**Pull request merged**
