### PR TITLE
Sort lanes IDs descending in connections

### PR DESCRIPTION
**Pull request by jakobkaths**
I found another instance where this reversed sorting is helpful for better overview.

### CODE REVIEW

**Comment by jakobkaths** [comment]
Yes, that's true, that could happen depending on the input, but I didn't observe it in any example. I added a new commit using lambda, I think that should be independent of what's coming in then. 
The reason I didn't observe the problem could be, because I need to set most of my links manually as create_junction(junction_roads, id, roads, name="my junction") in generators.py creates typically too many links. The connections in the junctions should only be made if the driving direction is allows. The other connection is done by predecessor / successor in the road. I tried to fix this by putting the _create_junction_links() functions in if/else conditions and thus drop the links in the wrong direction, but that doesn't work for all combinations either. If you want, I can push that, too, but it shouldn't be merged. Maybe that's a problem you are addressing anyways with your new junction generator?

**Comment by mander76** [comment]
That would be nice to look into, then the LHT, and RHT needs to be taken into account. The implementation of this was added before it could determine LHT and RHT so, all were created to handle both cases.

I'll try to look into that part of the junction creator, right now I think it will create the same connections as the previous funciton.

**Comment by mander76** [comment]
Could you start an issue, and we can keep track of it there?

**Comment by jakobkaths** [comment]
Yes, I created an issue and also uploaded my branch just for illustration of what I mean.

**Pull request merged**
