### PR TITLE
Fix overlaying repeating objects

### PR DESCRIPTION
**Pull request by jakobkaths**
- make sure s and length of repeat entries are used correctly for roads with multiple lane sections
- use multiple repeat entries for one object instead of multiple objects with one repeat entry

### CODE REVIEW

**Comment by jakobkaths** [comment]
Hi @mander76,  @MandolinMicke, could one of you have a look at this? Unfortunately back then I created a bug in this convenience function that led to repeating objects overlapping each other. I refactored a bit and the functionality is better now, too.

**Comment by MandolinMicke** [comment]
I'm having vacation this (and next week probably) so will check when I'm back. 
and FYI both are my accounts :P one is work and one is private :P

**Comment by jakobkaths** [comment]
> I'm having vacation this (and next week probably) so will check when I'm back. and FYI both are my accounts :P one is work and one is private :P

Haha, I thought you had another collaborator from Volvo. :-) No rush, enjoy your vacation!

**Comment by mander76** [comment]
Looks good!

**Comment by mander76** [comment]
I will not have time to create a new release until (earliest) late next week.

**Comment by jakobkaths** [comment]
Oh, that's no problem at all. Thanks for merging!

**Comment by jakobkaths** [comment]
@mander76 sorry for bugging you with this, but do you already have plans for the next release?

**Comment by mander76** [comment]
No problem.
Yes, I'll try to make one this week (probably tomorrow), more people have asked and a lot of small fixes has been merged lately.

**Comment by jakobkaths** [comment]
Great, thank you!

**Comment by mander76** [comment]
new release, had time today already :)

**Comment by jakobkaths** [comment]
Cool, thanks!

**Pull request merged**
