### PR TITLE
Consider laneoffsets for adjustment

### PR DESCRIPTION
**Pull request by jakobkaths**
Hi there, I didn't make a PR in a while, but I ran into an issue when I tried creating a road with merges and splits. I needed to consider the lane_offset as in scenariogeneration\examples\xodr\highway_example_with_merge_and_split.py line 102 and 114. However, if I had lanes that are not 3m wide, the adjustment of the planview was wrong. I tried to avoid that magic number "3" and hope I got all the directions right. For my example it works, but maybe you can try check it and make more detailed tests? I also tried to clean up a bit by avoiding code duplication.

### CODE REVIEW

**Comment by mander76** [comment]
I saw this the other day aswell, but haven't had time to fix it..  thanks for the fix!

**Comment by jakobkaths** [comment]
You're welcome, thanks for merging so quickly!

**Comment by mander76** [comment]
I'm working on a new junction creator functionality, that I hope I can merge soon, so now I can test some more things with that :)

**Comment by jakobkaths** [comment]
That sounds good, I'm curious to try that out. Are there any plans yet for the timing of the next release?

**Comment by mander76** [comment]
I hope in two weeks, I'm cramped at work atm... But all my progress is on the new_junction_creator branch if you wanna have a look. There are three examples there now I think

**Pull request merged**
