### PR TITLE
Linking and number of lanes

### PR DESCRIPTION
**Pull request by seawee1**
Hi, I'm quite certain that this has to be changed?

### CODE REVIEW

**Comment by seawee1** [comment]
I'm suspicious because you have
`
if len(pre_road.lanes.lanesections[pre_connecting_lanesec].leftlanes) == len(suc_road.lanes.lanesections[-1].leftlanes
`
in line 995 and
`
if len(pre_road.lanes.lanesections[pre_connecting_lanesec].rightlanes) == len(suc_road.lanes.lanesections[-1].rightlanes
`
in line 1022.

**Comment by seawee1** [comment]
Ah yes, I see. Makes sense 👍

**Comment by seawee1** [comment]
I guess you will incorporate this at some point without the need for a pull request?

**Comment by mander76** [comment]
Sure, will fix!
 good find!

**Comment by seawee1** [comment]
Nice. No problem. Only found it because I'm using this awesome repo in one of my work projects.
See: https://github.com/seawee1/driver-dojo if you're interested :)

**Comment by mander76** [comment]
Cool! Always nice to see different applications to scenariogeneration :)

**Pull request closed without merging**
