### PR TITLE
adding support for varying lane widths and offsets in junctions

### PR DESCRIPTION
**Pull request by Venky14062001**
Minor changes to the add_connections and following downstream functions

- This change brings in support for handling connections between roads that may have lanes with different widths (calculates offset point based on aggregated width of each lane, rather than using the first lane's width alone for the rest)
- This change also allows for generating connecting roads with varying lane widths (different start and end lane widths)

### CODE REVIEW

**Comment by mander76** [comment]
Wow, cool, will check this one out!

**Comment by mander76** [comment]
Two of the examples are failing, 
Think it is in cases when the lane widths are a polynomial (those examples has that at least)

**Comment by Venky14062001** [comment]
Addressed the failing examples, which happens when lane widths are exactly the same and the matrix loses dimensionality.
The case is only triggered if the lane_widths are different now :)

**Comment by mander76** [comment]
I can't get a simple example to work.

```
from scenariogeneration import xodr, esmini


road = xodr.create_road(geometry=xodr.Line(1000),
                        id=0,
                        left_lanes=2,
                        right_lanes=[xodr.LaneDef(400,500,2,3,-2)],
                        lane_width=3,
                        lane_width_end=3.5)

odr = xodr.OpenDrive("my road")
odr.add_road(road)
odr.adjust_roads_and_lanes()

esmini(odr,"<esminipath>")
```

Not sure what the lane_width_end is supposed to do, I think it should be part of the LaneDef definition instead, incase mutliple changes are needed?

**Comment by Venky14062001** [comment]
@mander76 the purpose of _lane_width_end_ was to be able to account for road geometries that may have lanes whose widths may change. This was done specifically to generate the road geometries for the connecting roads in the case of roads created using the **add_connection** function. The roads that **add_connection** function creates does not seem to involve lanes that are merging or splitting.

This example illustrates what the _lane_width_end_ is trying to achieve

`from scenariogeneration import xodr


road = xodr.create_road(geometry=xodr.Line(1000),
                        id=0,
                        left_lanes=2,
                        right_lanes=3,
                        lane_width=3,
                        lane_width_end=18)

odr = xodr.OpenDrive("my road")
odr.add_road(road)
odr.adjust_roads_and_lanes()

odr.write_xml("test.xodr")`

I did not test the changes with lanes that maybe splitting or merging. You maybe right about the fact that we may need to include this in either the definition of the road itself or the lane; or maybe just restrict the use of this to only when connecting roads are created using **add_connection** function.

**Comment by Venky14062001** [comment]
Let me know which approach would be better. I can make the corresponding changes.

**Comment by mander76** [comment]
Aha, now I get it, cool. Then there need to be some checks done (and written in the docstring)
So then LaneDef cannot be used at the same time (needs to be checked so that laneDef for lanes and lane_width_end are not used at the same time). 
Adding one example like this one and maybe one with junction would also be nice, then we can add some text to the user guide how to utilize it.

Very nice addition :)

**Comment by mander76** [comment]
I can write the user guide entry if you want, if you provide the two examples

**Comment by Venky14062001** [comment]
Sounds good! Will make the updates and add the examples!

**Comment by Venky14062001** [comment]
@mander76 I have made the updates. Do have a look and let me know if they are fine!

**Comment by mander76** [comment]
Great! Will try to look at the examples later today or tomorrow!

**Comment by mander76** [comment]
Black is failing right now

**Comment by Venky14062001** [comment]
ahh sorry about that, reformatted!

**Comment by mander76** [comment]
image
This doesn't look very good :P

**Comment by Venky14062001** [comment]
Can you send me the code used to generate this? The code changes do not really account for lane merging and splitting. I see some lane merging and splitting in this case. The changes are specifically meant for the functions **add_connection** and **_create_connecting_road_with_lane_input**. 

Here is a screenshot of the output of the example that I have added:

op

**Comment by mander76** [comment]
Sorry, my bad, something strange happened when I ran the example... don't know exactly what happened...

**Comment by mander76** [comment]
FYI, the reason I'm not making a release is that I'm taking this idea and expanding it to work in more cases.

**Comment by Venky14062001** [comment]
Sounds good. Will keep a look out for the updates. Thanks!

**Pull request merged**
