### PR TITLE
Add UserDefinedAction as separate class

### LINKED ISSUE #53: CustomCommandAction implemented with wrong parameters
The constructor of the CustomCommandAction class currently takes the following parameters:

```semimajoraxis,semiminoraxis,innerradius,offset,numberofvehicles,centralobject,trafficdefinition,velocity```

https://github.com/pyoscx/scenariogeneration/blob/1d94694a9029d22fb3ef46b0dbb90c7b068a66ae/scenariogeneration/xosc/actions.py#L3542

However, according to the OpenSCENARIO defition the CustomCommandAction has only one attribute:

```
- <xsd:complexType name="CustomCommandAction">
  - <xsd:simpleContent>
    - <xsd:extension base="xsd:string">
        <xsd:attribute name="type" type="String" use="required" /> 
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
```

### PR DESCRIPTION
**Pull request by nilsgoldbeck**
Fixes #53

### CODE REVIEW

**Comment by mander76** [comment]
Looks good, 
Two things though, all methods should have an __eq__ method implemented. If elementTrees cannot be compared, then always return False. 
Another is that is should have a staticmethod with parse(element) that should return the same object.

**Comment by nilsgoldbeck** [comment]
@mander76 Thanks for your comments. I've added the ```__eq__``` and ```parse``` methods. Does this look okay to you?

**Comment by mander76** [comment]
Look great! Now I'm only missing a test for the class ;)

**Comment by nilsgoldbeck** [comment]
I've added tests for the two new classes.
Any other comments @mander76?

**Comment by mander76** [comment]
Looks great!

**Pull request merged**
